###
GET https://jsonplaceholder.typicode.com/posts/
Accept: application/json

###
GET http://localhost:3000/api/heroes
Accept: application/json

###
DELETE http://localhost:3000/api/heroes/97e5caea-48ff-4ca9-b75e-80517ff6ee51
Accept: application/json

###
POST http://localhost:3000/api/heroes
Content-Type: application/json
Accept: application/json

{
  "firstName": "John",
  "lastName": "Doe",
  "knownAs": "JD",
  "house": "Florida"
}

###
PUT http://localhost:3000/api/heroes/5e7e9550-889b-4fbf-8b5c-ab5619a0ad70
Content-Type: application/json

{
  "firstName": "John - Updated",
  "lastName": "Doe - Updated",
  "knownAs": "JD - Updated",
  "house": "Florida - Updated"
}

